---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-6.7
    driver:
      box_url: file:///home/gkremer/src/vagrant-lxc-base-boxes/output/2016-03-16/vagrant-lxc-centos-6-amd64.box

suites:
  - name: default
    run_list:
      - recipe[ini_file::test]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
